language: python
python:
  - "3.6"      # current default Python on Travis CI
  # - "3.7"
  # - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - wget https://private.ed.ward.li/GoogleNews-vectors-negative300.bin.tar.gz
  - tar -zxvf GoogleNews-vectors-negative300.bin.tar.gz
# command to run tests
script:
  - pytest
